apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-woarpvku
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-woarpvku:fddb7d27280fdd4e6d1e1b3d8a5901bdb8655c6f@sha256:f72c8a8bf6a3581d8942c95a0b003d9209fc45e59ec43a2eeb3f6a4194da8e35
          name: container-image
